### ISSUE TITLE
ERROR (Yajl::ParseError): lexical error: invalid bytes in UTF8 string

### ISSUE THREAD

**Issue by Looooong** [delano/redis-dump#23]
```
ERROR (Yajl::ParseError): lexical error: invalid bytes in UTF8 string.
          t_courses.json:\fstartedl+\b�\f�da\u0001:\u0011machine_name\
                     (right here) ------^
```

**Comment by hiphip90** [comment]
Same here

**Comment by hiphip90** [comment]
Okay, did not read the README, my bad.

"If you have binary or serialized data in your Redis database, the YAJL parser may not load your dump file because it sees some of the binary data as 'invalid bytes in UTF8 string'. If you are certain that your data is binary and not malformed UTF8, you can use the -n flag to redis-load to tell YAJL to not check the input for UTF8 validity. Use with caution!"
