### ISSUE TITLE
TimeoutError

### ISSUE THREAD

**Issue by yisangwu** [delano/redis-dump#36]
ERROR (Redis::TimeoutError): Waited 1.0 seconds

# Redis Server
redis_version:7.0.12

Can you support the latest version?

**Comment by delano** [comment]
@yisangwu It supports Redis 7.x already. Based on the error, the issue you're having is related to the network connection. You can try increasing the timeout. 

```
$ bin/redis-dump -h
  Try: bin/redis-dump show-commands
Usage: bin/redis-dump [global options] COMMAND [command options] 
    ...

    -t, --timeout=S                  Configure connect, read, and write timeouts (ruby redis client)
```

Otherwise, if you still get the same error then the redis server either isn't running or isn't available to the machine running redis-dump.
